env:
  CIRRUS_CLONE_DEPTH: 1
  ARCH: amd64

task:
  freebsd_instance:
    matrix:
      image: freebsd-13-0-current-amd64-v20190510
      image: freebsd-12-0-release-amd64
      image: freebsd-11-2-release-amd64
  install_script:
    - sed -i.bak -e 's,pkg+http://pkg.FreeBSD.org/\${ABI}/quarterly,pkg+http://pkg.FreeBSD.org/\${ABI}/latest,' /etc/pkg/FreeBSD.conf
  script:
   - cc --version
   - export CFLAGS="-DITERATE=400 -DPAIRS_S=100 -DITERATIONS=24"
   - ./tools/ci-build.sh --cores=$(sysctl -n hw.ncpu)
   - make check
